x-app: &default-app
  build:
    context: "."
  restart: "unless-stopped"

services:
  web:
    <<: *default-app
    container_name: django-docker
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: "python manage.py runserver 0.0.0.0:8000"

  tailwind:
    <<: *default-app
    container_name: tailwind-watcher
    depends_on:
      - web
    command: "python manage.py tailwind start"
    volumes:
      - .:/app
      - node_modules:/app/theme/static_src/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
  node_modules:
